name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint_and_test:
    name: Linting and Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -e .[test]
          pip install pytest pytest-cov pylint python-dotenv toml tesults pytest-tesults

      # - name: Pylinting
      #   run: |
      #     source venv/bin/activate
      #     pylint export_snowflake/

      - name: Unit Tests
        run: |
          source venv/bin/activate
          pytest tests/unit -vv --cov export_snowflake --cov-fail-under=20

  integration_test:
    name: Integration Testing
    runs-on: ubuntu-latest
    environment: ci_tests
    strategy:
      matrix:
        python-version: [ 3.8 ]
    concurrency:
      group: integration_tests-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -e .[test]
          pip install pytest pytest-cov pylint python-dotenv toml tesults pytest-tesults

      - name: Integration tests
        run: |
          source venv/bin/activate
          pytest tests/integration/ -vvx --cov export_snowflake --cov-fail-under=20
        env:
          EXPORT_SNOWFLAKE_ACCOUNT: ${{ secrets.EXPORT_SNOWFLAKE_ACCOUNT }}
          EXPORT_SNOWFLAKE_DBNAME: ${{ secrets.EXPORT_SNOWFLAKE_DBNAME }}
          EXPORT_SNOWFLAKE_USER: ${{ secrets.EXPORT_SNOWFLAKE_USER }}
          EXPORT_SNOWFLAKE_PASSWORD: ${{ secrets.EXPORT_SNOWFLAKE_PASSWORD }}
          EXPORT_SNOWFLAKE_WAREHOUSE: ${{ secrets.EXPORT_SNOWFLAKE_WAREHOUSE }}
          EXPORT_SNOWFLAKE_SCHEMA: ${{ secrets.EXPORT_SNOWFLAKE_SCHEMA }}
          EXPORT_SNOWFLAKE_AWS_ACCESS_KEY: ${{ secrets.EXPORT_SNOWFLAKE_AWS_ACCESS_KEY }}
          EXPORT_SNOWFLAKE_AWS_SECRET_ACCESS_KEY: ${{ secrets.EXPORT_SNOWFLAKE_AWS_SECRET_ACCESS_KEY }}
          EXPORT_SNOWFLAKE_S3_BUCKET: ${{ secrets.EXPORT_SNOWFLAKE_S3_BUCKET }}
          EXPORT_SNOWFLAKE_S3_KEY_PREFIX: ${{ secrets.EXPORT_SNOWFLINK_S3_KEY_PREFIX }}
          EXPORT_SNOWFLAKE_STAGE: ${{ secrets.EXPORT_SNOWFLAKE_STAGE }}
          EXPORT_SNOWFLAKE_FILE_FORMAT_CSV: ${{ secrets.EXPORT_SNOWFLAKE_FILE_FORMAT_CSV }}
          EXPORT_SNOWFLAKE_FILE_FORMAT_PARQUET: ${{ secrets.EXPORT_SNOWFLAKE_FILE_FORMAT_PARQUET }}
          CLIENT_SIDE_ENCRYPTION_MASTER_KEY: ${{ secrets.EXPORT_SNOWFLAKE_CLIENT_SIDE_ENCRYPTION_MASTER_KEY }}